env:
  node: true
  commonjs: true
  es6: true
  jest: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  sourceType: module
overrides:
  files: ['**/*.ts']
  parser: '@typescript-eslint/parser'
  rules:
    no-undef: off
    no-unused-vars: off
